language: go

go:
  - 1.7
  - tip

install:
  - go get -u github.com/golang/dep/...
  # - go get -d -v -t ./...
  - dep ensure
  - go get github.com/haya14busa/goverage
  - go get github.com/haya14busa/gosum/cmd/gosumcheck

script:
  - go test -v -race $(go list ./... | grep -v "/vendor/")
  - goverage -coverprofile=coverage.txt ./...
  - (! gofmt -s -d *.go cmd | grep '^')
  - gosumcheck $(go list ./... | grep -v "/vendor/")

after_success:
  - bash <(curl -s https://codecov.io/bash)
